"""Deck image rendering: composes card thumbnails into a grid in canonical
deck order (UNIT → PILOT → COMMAND → BASE, ascending level then cost), with
a colored circular badge on each card showing its copy count.

Kept separate from tools.py because it returns PNG bytes, not JSON-serializable
data like every other tool implementation.
"""
from __future__ import annotations

import io
from functools import lru_cache
from pathlib import Path

import httpx
from PIL import Image as PILImage
from PIL import ImageDraw, ImageFont

from . import data, tools

# Disk cache of downloaded card art, keyed by card id, so re-renders across
# process restarts don't re-fetch images over the network.
_PROJECT_ROOT = Path(__file__).resolve().parent.parent
_IMAGE_CACHE_DIR = _PROJECT_ROOT / "data" / "cards" / "images"

# ~5:7 card aspect ratio; source art is 600x838, this stays legible without upsampling
THUMB_SIZE = (360, 504)
PADDING = 14
BADGE_RADIUS = 24
# distance from the card's right edge to the badge center, so it can't spill into the next card
BADGE_X_INSET = 34
# pushed down from the top edge so it doesn't cover the card's own corner id/rarity print
BADGE_Y_OFFSET = 72
BADGE_FONT_SIZE = 24
COLUMNS = 6

BG_COLOR = (18, 19, 22)
TITLE_COLOR = (234, 234, 234)
BADGE_FILL = (197, 48, 44)
BADGE_OUTLINE = (255, 255, 255)
PLACEHOLDER_BG = (40, 40, 46)
FOOTER_COLOR = (130, 130, 138)

FOOTER_TEXT = "generated by Kiraya"
FOOTER_FONT_SIZE = 13
FOOTER_LINE_HEIGHT = 15

STATS_ROW1_PANEL_COUNT = 3
STATS_ROW1_HEIGHT = 190
STATS_ROW_GAP = 22
STATS_HBAR_HEIGHT = 210  # height of each full-width horizontal-bar row (traits, pilot links)
STATS_PANEL_GAP = 16
STATS_TITLE_COLOR = (200, 200, 205)
STATS_LABEL_COLOR = (150, 150, 158)
STATS_VALUE_COLOR = (230, 230, 230)
STATS_BAR_COLOR = (90, 140, 210)
STATS_TITLE_FONT_SIZE = 21
STATS_LABEL_FONT_SIZE = 16
STATS_MAX_LABEL_CHARS = 10

COLOR_RGB = {
    "Red": (197, 48, 44),
    "Blue": (44, 112, 197),
    "Green": (44, 154, 79),
    "White": (217, 217, 217),
    "Purple": (123, 62, 197),
}

_FONT_CANDIDATES = [
    "/System/Library/Fonts/Supplemental/Arial Bold.ttf",  # macOS
    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",  # Linux
    "C:/Windows/Fonts/arialbd.ttf",  # Windows
]


@lru_cache(maxsize=8)
def _font(size: int) -> ImageFont.FreeTypeFont:
    for path in _FONT_CANDIDATES:
        try:
            return ImageFont.truetype(path, size)
        except OSError:
            continue
    return ImageFont.load_default()


def _fetch_image_bytes(url: str) -> bytes | None:
    try:
        resp = httpx.get(url, timeout=10.0, follow_redirects=True)
        resp.raise_for_status()
        return resp.content
    except httpx.HTTPError:
        return None


def _cache_path(card_id: str) -> Path:
    return _IMAGE_CACHE_DIR / f"{card_id}.png"


def _load_full_image(card: data.Card) -> PILImage.Image | None:
    """Return the full-resolution card art, backed by a disk cache under
    data/cards/images/<card_id>.png so re-renders across process restarts
    don't re-fetch over the network."""
    cache_path = _cache_path(card.id)
    if cache_path.exists():
        try:
            return PILImage.open(cache_path).convert("RGB")
        except OSError:
            pass  # corrupt cache file, fall through and re-fetch

    if not card.image_url:
        return None
    raw = _fetch_image_bytes(card.image_url)
    if not raw:
        return None
    try:
        img = PILImage.open(io.BytesIO(raw)).convert("RGB")
    except OSError:
        return None

    try:
        _IMAGE_CACHE_DIR.mkdir(parents=True, exist_ok=True)
        img.save(cache_path, format="PNG")
    except OSError:
        pass  # cache write failing shouldn't break rendering
    return img


def _placeholder_thumb(card: data.Card) -> PILImage.Image:
    img = PILImage.new("RGB", THUMB_SIZE, PLACEHOLDER_BG)
    draw = ImageDraw.Draw(img)
    border = COLOR_RGB.get(card.color or "", (80, 80, 90))
    draw.rectangle([0, 0, THUMB_SIZE[0] - 1, THUMB_SIZE[1] - 1], outline=border, width=4)
    font_size = 14 * THUMB_SIZE[0] // 150
    line_height = 18 * THUMB_SIZE[0] // 150
    font = _font(font_size)
    words = (card.name or card.id).split()
    lines: list[str] = []
    line = ""
    for w in words:
        candidate = f"{line} {w}".strip()
        if draw.textlength(candidate, font=font) > THUMB_SIZE[0] - 16:
            if line:
                lines.append(line)
            line = w
        else:
            line = candidate
    if line:
        lines.append(line)
    y = THUMB_SIZE[1] // 2 - (line_height * len(lines)) // 2
    for text_line in lines[:5]:
        draw.text((8, y), text_line, fill=(220, 220, 220), font=font)
        y += line_height
    return img


def _load_thumb(card: data.Card) -> PILImage.Image:
    img = _load_full_image(card)
    if img is not None:
        return img.resize(THUMB_SIZE)
    return _placeholder_thumb(card)


def _draw_badge(draw: ImageDraw.ImageDraw, cx: int, cy: int, count: int) -> None:
    r = BADGE_RADIUS
    draw.ellipse([cx - r, cy - r, cx + r, cy + r], fill=BADGE_FILL, outline=BADGE_OUTLINE, width=2)
    font = _font(BADGE_FONT_SIZE)
    text = str(count)
    bbox = draw.textbbox((0, 0), text, font=font)
    tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]
    draw.text((cx - tw / 2 - bbox[0], cy - th / 2 - bbox[1]), text, fill=(255, 255, 255), font=font)


def _truncate_label(label: str) -> str:
    if len(label) <= STATS_MAX_LABEL_CHARS:
        return label
    return label[: STATS_MAX_LABEL_CHARS - 1] + "…"


def _draw_mini_bar_chart(
    draw: ImageDraw.ImageDraw,
    x: float,
    y: float,
    w: float,
    h: float,
    title: str,
    bars: list[tuple[str, int | float]],
    bar_colors: list[tuple[int, int, int]] | None = None,
) -> None:
    """Draw a compact titled histogram: title on top, proportional bars with
    their value above each bar, and a truncated category label below."""
    title_font = _font(STATS_TITLE_FONT_SIZE)
    label_font = _font(STATS_LABEL_FONT_SIZE)
    draw.text((x, y), title, fill=STATS_TITLE_COLOR, font=title_font)

    axis_y = y + h - 20
    chart_top = y + 32
    chart_h = axis_y - chart_top
    value_label_space = 22  # reserved above the tallest bar so its value text can't reach the title
    bar_max_h = max(chart_h - value_label_space, 4)
    if not bars:
        return

    max_v = max(v for _, v in bars) or 1
    n = len(bars)
    gap = 6
    bar_w = max((w - gap * (n - 1)) / n, 4)

    for i, (label, value) in enumerate(bars):
        bx = x + i * (bar_w + gap)
        bar_h = bar_max_h * (value / max_v) if max_v else 0
        by = axis_y - bar_h
        color = bar_colors[i] if bar_colors else STATS_BAR_COLOR
        draw.rectangle([bx, by, bx + bar_w, axis_y], fill=color)

        vtext = str(value)
        vbox = draw.textbbox((0, 0), vtext, font=label_font)
        vw = vbox[2] - vbox[0]
        vpos = (bx + bar_w / 2 - vw / 2, by - 20)
        draw.text(vpos, vtext, fill=STATS_VALUE_COLOR, font=label_font)

        ltext = _truncate_label(str(label))
        lbox = draw.textbbox((0, 0), ltext, font=label_font)
        lw = lbox[2] - lbox[0]
        lpos = (bx + bar_w / 2 - lw / 2, axis_y + 4)
        draw.text(lpos, ltext, fill=STATS_LABEL_COLOR, font=label_font)


def _draw_horizontal_bar_chart(
    draw: ImageDraw.ImageDraw,
    x: float,
    y: float,
    w: float,
    h: float,
    title: str,
    bars: list[tuple[str, int | float]],
    bar_color: tuple[int, int, int] = STATS_BAR_COLOR,
) -> None:
    """Draw a titled horizontal histogram: full (untruncated) category labels
    on the left of each row, bars growing left-to-right, value at the end.
    Better fit for long labels (e.g. trait names) than vertical bars."""
    title_font = _font(STATS_TITLE_FONT_SIZE)
    label_font = _font(STATS_LABEL_FONT_SIZE)
    draw.text((x, y), title, fill=STATS_TITLE_COLOR, font=title_font)

    if not bars:
        return

    chart_top = y + 34
    n = len(bars)
    row_gap = 11
    row_h = max((h - 34 - row_gap * (n - 1)) / n, 10)

    label_w = max(draw.textlength(str(label), font=label_font) for label, _ in bars) + 10
    bar_x0 = x + label_w
    bar_max_w = max(w - label_w - 44, 10)  # reserve room for the value text past the bar end

    max_v = max(v for _, v in bars) or 1
    for i, (label, value) in enumerate(bars):
        ry = chart_top + i * (row_h + row_gap)
        bar_w = bar_max_w * (value / max_v) if max_v else 0

        ltext = str(label)
        lbox = draw.textbbox((0, 0), ltext, font=label_font)
        lw, lh = lbox[2] - lbox[0], lbox[3] - lbox[1]
        draw.text(
            (bar_x0 - lw - 8, ry + row_h / 2 - lh / 2 - lbox[1]),
            ltext, fill=STATS_LABEL_COLOR, font=label_font,
        )

        draw.rectangle([bar_x0, ry, bar_x0 + bar_w, ry + row_h], fill=bar_color)

        vtext = str(value)
        vbox = draw.textbbox((0, 0), vtext, font=label_font)
        vh = vbox[3] - vbox[1]
        draw.text(
            (bar_x0 + bar_w + 6, ry + row_h / 2 - vh / 2 - vbox[1]),
            vtext, fill=STATS_VALUE_COLOR, font=label_font,
        )


def _resolve_sequence(deck: dict[str, int]) -> list[tuple[data.Card, int]]:
    """Resolve a {card_id: count} dict to [(card, count), ...] in canonical
    deck order (data.deck_sort_key: UNIT → PILOT → COMMAND → BASE, then
    ascending level, then cost) regardless of input order."""
    resolved: list[tuple[data.Card, int]] = []
    for card_id, count in deck.items():
        card = data.get_card_by_id(card_id)
        if card is not None:
            resolved.append((card, count))
    resolved.sort(key=lambda entry: data.deck_sort_key(entry[0]))
    return resolved


def render_deck_image(
    main_deck: dict[str, int],
    resource_deck: dict[str, int] | None = None,
    title: str | None = None,
    show_stats: bool = False,
) -> bytes:
    """Render a deck as a PNG: one continuous grid of card thumbnails in
    canonical deck order — UNIT → PILOT → COMMAND → BASE, ascending level
    then cost within each type (main deck first, then resource deck if
    given). Each thumbnail has a red circular badge in the top-right corner
    giving its copy count. An optional `title` is drawn centered at the
    top, and a small "generated by Kiraya" credit is drawn bottom-left.

    If `show_stats` is True, computed via tools.analyze_deck_impl: a row of
    3 compact vertical histograms (cost curve, colors, types) is drawn below
    the card grid, then a full-width horizontal histogram of the top 5
    traits (horizontal so long trait names stay readable), then — if the
    deck has any Pilot/Pilot-capable cards linking to a Unit in the deck —
    one more horizontal histogram of each pilot's linkable-Unit-copy count.
    All above the footer. Returns raw PNG bytes.
    """
    cards = _resolve_sequence(main_deck)
    if resource_deck:
        cards += _resolve_sequence(resource_deck)

    tile_w = THUMB_SIZE[0] + PADDING
    tile_h = THUMB_SIZE[1] + PADDING + 6
    rows = -(-len(cards) // COLUMNS) if cards else 0
    width = PADDING + COLUMNS * tile_w

    title_font = _font(28)
    title_height = 50 if title else 0
    footer_height = FOOTER_LINE_HEIGHT + PADDING

    stats = tools.analyze_deck_impl(main_deck) if show_stats else None
    pilot_bars = [(label, n) for label, n in stats["pilot_link_counts"] if n > 0] if stats else []
    stats_height = 0
    if show_stats:
        stats_height = STATS_ROW1_HEIGHT + STATS_ROW_GAP + STATS_HBAR_HEIGHT + PADDING
        if pilot_bars:
            stats_height += STATS_ROW_GAP + STATS_HBAR_HEIGHT

    grid_top = PADDING + title_height
    stats_top = grid_top + rows * tile_h + PADDING
    total_h = grid_top + rows * tile_h + stats_height + footer_height

    canvas = PILImage.new("RGB", (width, max(total_h, 100)), BG_COLOR)
    draw = ImageDraw.Draw(canvas)

    if title:
        bbox = draw.textbbox((0, 0), title, font=title_font)
        tw = bbox[2] - bbox[0]
        title_pos = ((width - tw) / 2 - bbox[0], PADDING - bbox[1])
        draw.text(title_pos, title, fill=TITLE_COLOR, font=title_font)

    for i, (card, count) in enumerate(cards):
        col, row = i % COLUMNS, i // COLUMNS
        x = PADDING + col * tile_w
        ty = grid_top + row * tile_h
        canvas.paste(_load_thumb(card), (x, ty))
        _draw_badge(draw, x + THUMB_SIZE[0] - BADGE_X_INSET, ty + BADGE_Y_OFFSET, count)

    if show_stats:
        cost_curve_items = stats["cost_curve"].items()
        cost_bars = [
            (str(k), v)
            for k, v in sorted(cost_curve_items, key=lambda kv: (isinstance(kv[0], str), kv[0]))
        ]
        color_bars = list(stats["color_breakdown"].items())
        color_bar_colors = [COLOR_RGB.get(k, STATS_BAR_COLOR) for k, _ in color_bars]
        type_bars = list(stats["type_breakdown"].items())
        trait_bars = [(name, n) for name, n in stats["top_traits"][:5]]

        row1_panels: list[tuple[str, list[tuple[str, int]], list[tuple[int, int, int]] | None]] = [
            (f"Cost curve (avg {stats['average_cost']})", cost_bars, None),
            ("Colors", color_bars, color_bar_colors),
            ("Types", type_bars, None),
        ]
        panel_w = (
            width - PADDING - (STATS_ROW1_PANEL_COUNT - 1) * STATS_PANEL_GAP - PADDING
        ) / STATS_ROW1_PANEL_COUNT
        for i, (ptitle, bars, colors) in enumerate(row1_panels):
            px = PADDING + i * (panel_w + STATS_PANEL_GAP)
            _draw_mini_bar_chart(
                draw, px, stats_top, panel_w, STATS_ROW1_HEIGHT, ptitle, bars, colors
            )

        traits_top = stats_top + STATS_ROW1_HEIGHT + STATS_ROW_GAP
        traits_w = width - 2 * PADDING
        _draw_horizontal_bar_chart(
            draw, PADDING, traits_top, traits_w, STATS_HBAR_HEIGHT, "Top traits", trait_bars
        )

        if pilot_bars:
            pilots_top = traits_top + STATS_HBAR_HEIGHT + STATS_ROW_GAP
            _draw_horizontal_bar_chart(
                draw, PADDING, pilots_top, width - 2 * PADDING, STATS_HBAR_HEIGHT,
                "Pilot -> linkable Units", pilot_bars,
            )

    footer_font = _font(FOOTER_FONT_SIZE)
    footer_y = total_h - footer_height + PADDING // 2
    draw.text((PADDING, footer_y), FOOTER_TEXT, fill=FOOTER_COLOR, font=footer_font)

    buf = io.BytesIO()
    canvas.save(buf, format="PNG")
    return buf.getvalue()
